import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import { InvitationCard } from "@/components/card/InvitationCard";
import { GENERATION_STALE_SECONDS } from "@/lib/ai/generations.server";
import { hashRateLimitKey } from "@/lib/auth/rate-limit";
import { generatedTextLayer } from "@/lib/card/card-text.server";
import type { CardPanel } from "@/lib/card/card-data";
import { cardContent } from "@/lib/card/facts";
import type { CardLayoutId } from "@/lib/card/layouts";
import { proportionOf, type CardShape } from "@/lib/card/shapes";
import type { TypographyPairingId } from "@/lib/card/typography";
import { generationEnv } from "@/lib/env";
import { provisionalContent } from "@/lib/events/provisional";
import { CARD_ART_BUCKET, runGeneration } from "@/lib/generation/run.server";
import { createAdminClient } from "@/lib/supabase/admin";

import { launchChromium } from "../fixtures/browser";
import { startStaticServer } from "../fixtures/static-server";

/**
 * The creative-understanding corpus through the production pipeline (`docs/model-contracts.md
 * §6`; `docs/development-plan.md`, Phase 5 exit): each case becomes a real event on a hosted
 * Supabase project, generated by `runGeneration` exactly as the server runs it — metered, capped,
 * persisted — and its stored card is then drawn by `InvitationCard` in Chromium for a person to
 * judge.
 *
 * Opt-in and live: it runs only with `LIVE_CORPUS=1`, through `scripts/corpus/run-live.mjs`,
 * which points it at a project and switches generation on for this process alone. It makes real,
 * metered model calls (about $0.10 a card) under the project's daily ceiling. Output: one PNG and
 * one summary row per case in `CORPUS_OUT`.
 *
 * As the host first sees it: the card's facts are the event's own fields, so cases whose host
 * confirmed nothing show the Creation Mode placeholders (§7.3); CU-11's stated facts are set as
 * if the host confirmed them during the wait.
 */

const LIVE = process.env.LIVE_CORPUS === "1";
const OUT = process.env.CORPUS_OUT ?? path.resolve("corpus-out");
const ONLY = (process.env.CORPUS_CASES ?? "").split(",").filter(Boolean);
const CONCURRENCY = Number(process.env.CORPUS_CONCURRENCY ?? "2");
const RUNNER_EMAIL = "corpus-runner@example.com";

interface CorpusCase {
  id: string;
  prompt: string;
  class?: string;
  mustAvoid?: string[];
}

/** The owner's two Phase 3 briefs (`docs/model-evals/phase-3-validation.md`). */
const OWNER_BRIEFS: CorpusCase[] = [
  {
    id: "O-01",
    prompt:
      "Spring engagement brunch at a garden venue. Romantic and fresh with soft florals, citrus, warm cream, sage and a little terracotta. Elegant but relaxed — not rustic farmhouse, not overly formal, and definitely not generic wedding-template vibes.",
    mustAvoid: ["rustic farmhouse", "generic wedding-template"],
  },
  {
    id: "O-02",
    prompt:
      "Baby shower that's Ralph Lauren bear themed, dark navys and browns, not overly baby but still says this is for a baby shower.",
  },
];

/** Facts CU-11's host states, as the details form would store them once confirmed. */
const CONFIRMED: Record<string, Record<string, string>> = {
  "CU-11": {
    event_date: "2026-12-19",
    start_time: "13:00",
    venue_name: "The Lodge at Hanson Park",
    address: "Aldie, Virginia",
  },
};

function corpus(): CorpusCase[] {
  const file = path.resolve("docs/model-evals/creative-understanding.json");
  const { cases } = JSON.parse(readFileSync(file, "utf8")) as { cases: CorpusCase[] };
  const all = [...cases, ...OWNER_BRIEFS];
  return ONLY.length ? all.filter((c) => ONLY.includes(c.id)) : all;
}

type Admin = ReturnType<typeof createAdminClient>;

async function runnerUser(admin: Admin): Promise<string> {
  const created = await admin.auth.admin.createUser({ email: RUNNER_EMAIL, email_confirm: true });
  if (created.data.user) return created.data.user.id;
  for (let page = 1; page <= 20; page += 1) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw error;
    const user = data.users.find((u) => u.email === RUNNER_EMAIL);
    if (user) return user.id;
    if (data.users.length < 200) break;
  }
  throw created.error ?? new Error("could not create or find the corpus runner");
}

const keyHash = (key: string) => `\\x${hashRateLimitKey(key).toString("hex")}`;

interface CaseResult {
  id: string;
  prompt: string;
  eventId: string;
  generationId: string | null;
  start: string;
  status: string;
  errorCode: string | null;
  wallMs: number;
  costUsd: number;
  calls: Record<string, number>;
  telemetry: unknown;
  design?: {
    name: string;
    description: string;
    shape: CardShape;
    layout: CardLayoutId;
    artMode: string;
    primary: TypographyPairingId;
    title: string;
    invitationLine: string;
    artBrief: unknown;
    standardWordingSlots: string[];
  };
  panel?: boolean;
  png?: string;
  renderError?: string;
}

async function generate(admin: Admin, userId: string, c: CorpusCase): Promise<CaseResult> {
  const began = Date.now();
  const { data: event, error: eventError } = await admin
    .from("events")
    .insert({
      owner_id: userId,
      prompt: c.prompt,
      generation_requested_at: new Date().toISOString(),
    })
    .select("id")
    .single();
  if (eventError) throw eventError;
  const env = generationEnv();
  const { data: started, error: startError } = await admin.rpc("start_generation", {
    p_event_id: event.id,
    p_user_id: userId,
    p_kind: "initial",
    p_idempotency_key: randomUUID(),
    p_event_key_hash: keyHash(`event:${event.id}`),
    p_host_key_hash: keyHash(`user:${userId}`),
    p_event_cap: env.eventDailyCap,
    p_host_cap: env.hostDailyCap,
    p_stale_seconds: GENERATION_STALE_SECONDS,
  });
  if (startError) throw startError;
  const row = Array.isArray(started) ? started[0] : started;
  const base = { id: c.id, prompt: c.prompt, eventId: event.id, costUsd: 0, calls: {} };
  if (!row?.generation_id || row.outcome !== "started") {
    return {
      ...base,
      generationId: null,
      start: String(row?.outcome),
      status: "not_started",
      errorCode: null,
      wallMs: Date.now() - began,
      telemetry: null,
    };
  }
  const generationId: string = row.generation_id;
  await runGeneration({ generationId, eventId: event.id, userId });

  const { data: generation, error: readError } = await admin
    .from("generations")
    .select("status, error_code, telemetry, card_design_id")
    .eq("id", generationId)
    .single();
  if (readError) throw readError;
  const { data: runs, error: runsError } = await admin
    .from("generation_runs")
    .select("operation, cost_estimate_usd")
    .eq("generation_id", generationId);
  if (runsError) throw runsError;
  const calls: Record<string, number> = {};
  let costUsd = 0;
  for (const run of runs ?? []) {
    calls[run.operation] = (calls[run.operation] ?? 0) + 1;
    costUsd += Number(run.cost_estimate_usd ?? 0);
  }
  return {
    ...base,
    generationId,
    start: row.outcome,
    status: generation.status,
    errorCode: generation.error_code,
    wallMs: Date.now() - began,
    costUsd: Math.round(costUsd * 10_000) / 10_000,
    calls,
    telemetry: generation.telemetry,
  };
}

async function pool<T, R>(items: T[], size: number, work: (item: T) => Promise<R>): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.max(1, size) }, async () => {
      while (next < items.length) {
        const i = next++;
        results[i] = await work(items[i]);
      }
    }),
  );
  return results;
}

interface ZoneInk {
  ink: string;
  panel?: Omit<CardPanel, "color">;
  panelColor?: string;
}

describe.skipIf(!LIVE)("the corpus through the production pipeline (live)", () => {
  it("generates, persists and draws every case", { timeout: 3_600_000 }, async () => {
    const admin = createAdminClient();
    const userId = await runnerUser(admin);
    mkdirSync(OUT, { recursive: true });

    const cases = corpus();
    const results = await pool(cases, CONCURRENCY, async (c) => {
      try {
        const result = await generate(admin, userId, c);
        console.log(`${c.id}: ${result.status}${result.errorCode ? ` (${result.errorCode})` : ""}`);
        return result;
      } catch (error) {
        console.log(`${c.id}: runner error ${(error as Error).message}`);
        return {
          id: c.id,
          prompt: c.prompt,
          eventId: "",
          generationId: null,
          start: "runner_error",
          status: "runner_error",
          errorCode: (error as Error).message,
          wallMs: 0,
          costUsd: 0,
          calls: {},
          telemetry: null,
        } satisfies CaseResult;
      }
    });

    const server = await startStaticServer();
    const browser = await launchChromium();
    try {
      const page = await browser.newPage({ deviceScaleFactor: 2 });
      for (const result of results) {
        if (result.status !== "succeeded" || !result.generationId) continue;
        try {
          const { data: design, error } = await admin
            .from("card_designs")
            .select(
              "id, name, description, shape, layout, art_mode, typography, wording, art_brief, standard_wording_slots",
            )
            .eq("event_id", result.eventId)
            .order("round", { ascending: false })
            .limit(1)
            .single();
          if (error) throw error;
          const { data: asset, error: assetError } = await admin
            .from("card_art_assets")
            .select("storage_key, ink")
            .eq("card_design_id", design.id)
            .order("created_at", { ascending: false })
            .limit(1)
            .single();
          if (assetError) throw assetError;
          const download = await admin.storage.from(CARD_ART_BUCKET).download(asset.storage_key);
          if (download.error) throw download.error;
          const bytes = Buffer.from(await download.data.arrayBuffer());

          const shape = design.shape as CardShape;
          const layout = design.layout as CardLayoutId;
          const typography = design.typography as { primary: TypographyPairingId };
          const wording = design.wording as { title: string; invitationLine: string };
          const zone = (asset.ink as unknown as Record<string, Record<string, ZoneInk>>)[shape]
            .text;
          const confirmed = CONFIRMED[result.id] ?? {};
          const placeholders = provisionalContent({}, new Date());
          const content = cardContent({
            title: wording.title,
            invitationLine: wording.invitationLine,
            babyName: null,
            hosts: null,
            eventDate: confirmed.event_date ?? placeholders.eventDate.value,
            startTime: confirmed.start_time ?? placeholders.startTime.value,
            endTime: null,
            venueName: confirmed.venue_name ?? placeholders.venue.value,
            address: confirmed.address ?? null,
            rsvpDeadline: null,
            timezone: null,
          });
          const boxes = await generatedTextLayer({
            layout,
            shape,
            pairing: typography.primary,
            content,
            ink: zone.ink,
          });
          const panels: CardPanel[] =
            zone.panel && zone.panelColor ? [{ ...zone.panel, color: zone.panelColor }] : [];
          const markup = renderToStaticMarkup(
            createElement(InvitationCard, {
              shape,
              artwork: {
                src: `data:image/png;base64,${bytes.toString("base64")}`,
                proportion: proportionOf(shape),
              },
              panels,
              boxes,
            }),
          );
          const pathname = `/corpus/${result.id}.html`;
          server.put(
            pathname,
            `<!doctype html><html lang="en"><head><meta charset="utf-8">` +
              `<link rel="stylesheet" href="/card-fonts.css">` +
              `<style>html,body{margin:0;background:#f4f1ec}main{width:560px;padding:24px}</style>` +
              `</head><body><main>${markup}</main></body></html>`,
            "text/html; charset=utf-8",
          );
          await page.goto(`${server.origin}${pathname}`);
          await page.evaluate(async () => {
            await document.fonts.ready;
            await Promise.all(
              [...document.images].map((img) => (img.complete ? null : img.decode())),
            );
          });
          const png = path.join(OUT, `${result.id}.png`);
          await page.locator("[data-invitation-card]").screenshot({ path: png });
          result.png = path.basename(png);
          result.panel = panels.length > 0;
          result.design = {
            name: design.name,
            description: design.description,
            shape,
            layout,
            artMode: design.art_mode,
            primary: typography.primary,
            title: wording.title,
            invitationLine: wording.invitationLine,
            artBrief: design.art_brief,
            standardWordingSlots: design.standard_wording_slots,
          };
        } catch (error) {
          result.renderError = (error as Error).message;
          console.log(`${result.id}: render error ${result.renderError}`);
        }
      }
    } finally {
      await browser.close();
      await server.close();
    }

    writeFileSync(path.join(OUT, "summary.json"), JSON.stringify(results, null, 2));
    const succeeded = results.filter((r) => r.status === "succeeded").length;
    const cost = results.reduce((sum, r) => sum + r.costUsd, 0);
    console.log(`${succeeded}/${results.length} succeeded; $${cost.toFixed(2)} metered`);
    expect(results.length).toBe(cases.length);
  });
});
