// Phase A.1 hand-composed set: the twelve Phase A sites carried over (each now declares its hero variant),
// plus four sites exercising the four new hero recipes and the fifth RSVP shell.
// Every visible decision traces to vocab.js: family rule · named recipe · variant · PageSystem value ·
// composition value · quantized parameter · motif assignment. No site carries a bespoke override.
// Changes from Phase A, all rule-driven: heroSplit is quantized to [.38,.50,.62] (01 was .55);
// rsvp_contained_card is excluded on framed surfaces (02, 11 moved); state_plate was dropped (02, 05, 07, 11);
// plan rhythm/contrast must match composition (06, 07); strong asymmetry maps heroSplit to .62 (08);
// family button/card lists (09, 10); axis-requiring section recipes (10 registry, 11 details).

window.SITES = [
  {
    id: "01", name: "Deep Editorial", family: "editorial", tonalDirection: "dark",
    heroRecipe: "editorial_split", heroVariant: "field_right", detailsRecipe: "details_split_panel", rsvpRecipe: "rsvp_contrast_split", registryRecipe: "registry_featured", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP1_dark_opening", border: "hairline", card: "outlined", button: "solid_rounded" },
    composition: { asymmetry: "strong", hierarchy: "editorial", rhythm: "alternating", sectionContrast: "high", ornament: "restrained" },
    typography: "heritage_caslon_karla", density: "spacious",
    parameters: { heroSplit: 0.62, heroHeight: "full", alignOffset: 2, measure: "standard", bandHeight: "medium", motifScale: 1.5, motifOpacity: 0.14, borderWeight: 1, displayTracking: -0.02 },
    motifs: [{ id: "plaid", slot: "field" }, { id: "equestrian", slot: "accent" }],
  },
  {
    id: "02", name: "Winter Invitation", family: "invitation", tonalDirection: "light",
    heroRecipe: "framed_invitation", heroVariant: "thin_frame", detailsRecipe: "details_stacked", rsvpRecipe: "rsvp_typographic_stack", registryRecipe: "registry_tiles", stateRecipe: "state_quiet",
    pageSystem: { axis: "center", surfacePlan: "SP5_framed_body", border: "double", card: "outlined", button: "outline_square" },
    composition: { asymmetry: "symmetric", hierarchy: "restrained", rhythm: "continuous", sectionContrast: "low", ornament: "decorative" },
    typography: "hc_bodoni_inter", density: "balanced",
    parameters: { heroSplit: 0.50, heroHeight: "full", alignOffset: 0, measure: "narrow", bandHeight: "thin", motifScale: 1, motifOpacity: 0.22, borderWeight: 2, displayTracking: 0 },
    motifs: [{ id: "equestrian", slot: "accent" }, { id: "linen", slot: "frame" }],
  },
  {
    id: "03", name: "Modern Club", family: "statement", tonalDirection: "mid",
    heroRecipe: "typography_first", heroVariant: "band_below", detailsRecipe: "details_grid", rsvpRecipe: "rsvp_typographic_stack", registryRecipe: "registry_uneven_grid", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP3_interrupted", border: "accented", card: "tinted", button: "solid_square" },
    composition: { asymmetry: "gentle", hierarchy: "monumental", rhythm: "punctuated", sectionContrast: "moderate", ornament: "none" },
    typography: "grotesk_archivo_inter", density: "compact",
    parameters: { heroSplit: 0.50, heroHeight: "standard", alignOffset: 0, measure: "wide", bandHeight: "medium", motifScale: 2.25, motifOpacity: 0.22, borderWeight: 3, displayTracking: -0.05 },
    motifs: [{ id: "stripe", slot: "band" }],
  },
  {
    id: "04", name: "Lodge Gazette", family: "editorial", tonalDirection: "light",
    heroRecipe: "editorial_masthead", heroVariant: "rail_right", detailsRecipe: "details_sidebar_rows", rsvpRecipe: "rsvp_edge_interruption", registryRecipe: "registry_editorial_list", stateRecipe: "state_quiet",
    pageSystem: { axis: "alternating", surfacePlan: "SP2_continuous_light", border: "hairline", card: "flat", button: "underline" },
    composition: { asymmetry: "gentle", hierarchy: "editorial", rhythm: "continuous", sectionContrast: "low", ornament: "restrained" },
    typography: "transitional_newsreader_tight", density: "balanced",
    parameters: { heroSplit: 0.50, heroHeight: "compact", alignOffset: 1, measure: "wide", bandHeight: "thin", motifScale: 0.75, motifOpacity: 0.35, borderWeight: 1, displayTracking: -0.02 },
    motifs: [{ id: "stripe", slot: "band" }, { id: "botanical", slot: "divider" }],
  },
  {
    id: "05", name: "Night Paddock", family: "editorial", tonalDirection: "dark",
    heroRecipe: "editorial_offset", heroVariant: "plate_left", detailsRecipe: "details_sidebar_rows", rsvpRecipe: "rsvp_contained_card", registryRecipe: "registry_uneven_grid", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP4_alternating", border: "accented", card: "plate", button: "solid_square" },
    composition: { asymmetry: "strong", hierarchy: "dramatic", rhythm: "alternating", sectionContrast: "high", ornament: "restrained" },
    typography: "hc_playfair_dmsans", density: "balanced",
    parameters: { heroSplit: 0.62, heroHeight: "full", alignOffset: 3, measure: "standard", bandHeight: "medium", motifScale: 1.5, motifOpacity: 0.14, borderWeight: 3, displayTracking: -0.02 },
    motifs: [{ id: "gingham", slot: "field" }, { id: "equestrian", slot: "accent" }],
  },
  {
    id: "06", name: "Evergreen Card", family: "invitation", tonalDirection: "mid",
    heroRecipe: "invitation_card", heroVariant: "floating", detailsRecipe: "details_grid", rsvpRecipe: "rsvp_typographic_stack", registryRecipe: "registry_tiles", stateRecipe: "state_quiet",
    pageSystem: { axis: "center", surfacePlan: "SP6_deepening", border: "hairline", card: "tinted", button: "outline_square" },
    composition: { asymmetry: "symmetric", hierarchy: "restrained", rhythm: "alternating", sectionContrast: "moderate", ornament: "decorative" },
    typography: "oldstyle_cormorant_figtree", density: "spacious",
    parameters: { heroSplit: 0.50, heroHeight: "full", alignOffset: 0, measure: "narrow", bandHeight: "thin", motifScale: 1, motifOpacity: 0.14, borderWeight: 1, displayTracking: 0.06 },
    motifs: [{ id: "linen", slot: "field" }, { id: "botanical", slot: "divider" }],
  },
  {
    id: "07", name: "Letterhead", family: "invitation", tonalDirection: "light",
    heroRecipe: "invitation_monogram", heroVariant: "crest", detailsRecipe: "details_stacked", rsvpRecipe: "rsvp_edge_interruption", registryRecipe: "registry_featured", stateRecipe: "state_quiet",
    pageSystem: { axis: "center", surfacePlan: "SP2_continuous_light", border: "double", card: "plate", button: "solid_square" },
    composition: { asymmetry: "symmetric", hierarchy: "editorial", rhythm: "continuous", sectionContrast: "low", ornament: "decorative" },
    typography: "heritage_baskerville_inter", density: "balanced",
    parameters: { heroSplit: 0.50, heroHeight: "standard", alignOffset: 0, measure: "narrow", bandHeight: "thin", motifScale: 1, motifOpacity: 0.35, borderWeight: 2, displayTracking: 0.14 },
    motifs: [{ id: "equestrian", slot: "accent" }, { id: "celestial", slot: "divider" }],
  },
  {
    id: "08", name: "Big Sky Stack", family: "statement", tonalDirection: "dark",
    heroRecipe: "statement_stack", heroVariant: "alternate", detailsRecipe: "details_split_panel", rsvpRecipe: "rsvp_edge_interruption", registryRecipe: "registry_editorial_list", stateRecipe: "state_quiet",
    pageSystem: { axis: "alternating", surfacePlan: "SP4_alternating", border: "none", card: "flat", button: "solid_square" },
    composition: { asymmetry: "strong", hierarchy: "monumental", rhythm: "alternating", sectionContrast: "high", ornament: "restrained" },
    typography: "grotesk_space_sourcesans", density: "compact",
    parameters: { heroSplit: 0.62, heroHeight: "full", alignOffset: 2, measure: "wide", bandHeight: "medium", motifScale: 1, motifOpacity: 0.08, borderWeight: 1, displayTracking: -0.05 },
    motifs: [{ id: "celestial", slot: "accent" }],
  },
  {
    id: "09", name: "Cream Editorial", family: "editorial", tonalDirection: "light",
    heroRecipe: "editorial_split", heroVariant: "field_left", detailsRecipe: "details_grid", rsvpRecipe: "rsvp_typographic_stack", registryRecipe: "registry_tiles", stateRecipe: "state_quiet",
    pageSystem: { axis: "alternating", surfacePlan: "SP6_deepening", border: "double", card: "tinted", button: "solid_square" },
    composition: { asymmetry: "gentle", hierarchy: "dramatic", rhythm: "alternating", sectionContrast: "moderate", ornament: "restrained" },
    typography: "soft_fraunces_manrope", density: "spacious",
    parameters: { heroSplit: 0.38, heroHeight: "standard", alignOffset: 1, measure: "standard", bandHeight: "thin", motifScale: 0.75, motifOpacity: 0.22, borderWeight: 2, displayTracking: 0 },
    motifs: [{ id: "linen", slot: "field" }, { id: "botanical", slot: "accent" }],
  },
  {
    id: "10", name: "Midnight Frame", family: "invitation", tonalDirection: "dark",
    heroRecipe: "framed_invitation", heroVariant: "deep_margin", detailsRecipe: "details_grid", rsvpRecipe: "rsvp_contained_card", registryRecipe: "registry_editorial_list", stateRecipe: "state_quiet",
    pageSystem: { axis: "center", surfacePlan: "SP1_dark_opening", border: "hairline", card: "tinted", button: "solid_square" },
    composition: { asymmetry: "symmetric", hierarchy: "dramatic", rhythm: "alternating", sectionContrast: "high", ornament: "restrained" },
    typography: "transitional_instrument_manrope", density: "compact",
    parameters: { heroSplit: 0.50, heroHeight: "full", alignOffset: 0, measure: "standard", bandHeight: "tall", motifScale: 1.5, motifOpacity: 0.14, borderWeight: 1, displayTracking: 0 },
    motifs: [{ id: "plaid", slot: "frame" }, { id: "celestial", slot: "accent" }],
  },
  {
    id: "11", name: "Cream Poster", family: "statement", tonalDirection: "light",
    heroRecipe: "typography_first", heroVariant: "band_rail", detailsRecipe: "details_sidebar_rows", rsvpRecipe: "rsvp_wide_heading", registryRecipe: "registry_featured", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP5_framed_body", border: "double", card: "outlined", button: "underline" },
    composition: { asymmetry: "gentle", hierarchy: "monumental", rhythm: "continuous", sectionContrast: "low", ornament: "restrained" },
    typography: "hc_bodoni_inter", density: "spacious",
    parameters: { heroSplit: 0.50, heroHeight: "standard", alignOffset: 0, measure: "narrow", bandHeight: "thin", motifScale: 1, motifOpacity: 0.14, borderWeight: 2, displayTracking: 0.06 },
    motifs: [{ id: "gingham", slot: "band" }],
  },
  {
    id: "12", name: "Forest Masthead", family: "editorial", tonalDirection: "mid",
    heroRecipe: "editorial_masthead", heroVariant: "band_top", detailsRecipe: "details_split_panel", rsvpRecipe: "rsvp_contrast_split", registryRecipe: "registry_uneven_grid", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP3_interrupted", border: "hairline", card: "outlined", button: "solid_rounded" },
    composition: { asymmetry: "gentle", hierarchy: "restrained", rhythm: "punctuated", sectionContrast: "moderate", ornament: "restrained" },
    typography: "oldstyle_garamond_worksans", density: "compact",
    parameters: { heroSplit: 0.50, heroHeight: "compact", alignOffset: 0, measure: "standard", bandHeight: "tall", motifScale: 1.5, motifOpacity: 0.14, borderWeight: 1, displayTracking: 0.06 },
    motifs: [{ id: "plaid", slot: "band" }, { id: "equestrian", slot: "divider" }],
  },
  // ---- new in A.1: one site per new hero recipe ----
  {
    id: "13", name: "Date Rail", family: "editorial", tonalDirection: "light",
    heroRecipe: "editorial_daterail", heroVariant: "rail_left", detailsRecipe: "details_grid", rsvpRecipe: "rsvp_wide_heading", registryRecipe: "registry_uneven_grid", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP4_alternating", border: "hairline", card: "outlined", button: "solid_square" },
    composition: { asymmetry: "gentle", hierarchy: "dramatic", rhythm: "alternating", sectionContrast: "high", ornament: "restrained" },
    typography: "transitional_newsreader_tight", density: "balanced",
    parameters: { heroSplit: 0.50, heroHeight: "standard", alignOffset: 1, measure: "standard", bandHeight: "medium", motifScale: 1, motifOpacity: 0.22, borderWeight: 1, displayTracking: -0.02 },
    motifs: [{ id: "botanical", slot: "divider" }, { id: "celestial", slot: "accent" }],
  },
  {
    id: "14", name: "Admit One", family: "invitation", tonalDirection: "mid",
    heroRecipe: "invitation_ticket", heroVariant: "stub_right", detailsRecipe: "details_stacked", rsvpRecipe: "rsvp_contained_card", registryRecipe: "registry_tiles", stateRecipe: "state_quiet",
    pageSystem: { axis: "center", surfacePlan: "SP6_deepening", border: "double", card: "plate", button: "outline_square" },
    composition: { asymmetry: "symmetric", hierarchy: "editorial", rhythm: "alternating", sectionContrast: "moderate", ornament: "decorative" },
    typography: "soft_dmserif_dmsans", density: "balanced",
    parameters: { heroSplit: 0.50, heroHeight: "standard", alignOffset: 0, measure: "narrow", bandHeight: "medium", motifScale: 1.5, motifOpacity: 0.22, borderWeight: 2, displayTracking: 0.06 },
    motifs: [{ id: "plaid", slot: "frame" }, { id: "celestial", slot: "divider" }],
  },
  {
    id: "15", name: "Nineteen", family: "statement", tonalDirection: "dark",
    heroRecipe: "statement_numeral", heroVariant: "numeral_left", detailsRecipe: "details_split_panel", rsvpRecipe: "rsvp_contrast_split", registryRecipe: "registry_editorial_list", stateRecipe: "state_quiet",
    pageSystem: { axis: "left", surfacePlan: "SP1_dark_opening", border: "accented", card: "tinted", button: "solid_square" },
    composition: { asymmetry: "strong", hierarchy: "monumental", rhythm: "alternating", sectionContrast: "high", ornament: "none" },
    typography: "grotesk_archivo_inter", density: "compact",
    parameters: { heroSplit: 0.62, heroHeight: "full", alignOffset: 2, measure: "wide", bandHeight: "tall", motifScale: 1, motifOpacity: 0.22, borderWeight: 2, displayTracking: -0.05 },
    motifs: [{ id: "stripe", slot: "band" }],
  },
  {
    id: "16", name: "Rule Grid", family: "editorial", tonalDirection: "light",
    heroRecipe: "editorial_rulegrid", heroVariant: "cells", detailsRecipe: "details_sidebar_rows", rsvpRecipe: "rsvp_edge_interruption", registryRecipe: "registry_featured", stateRecipe: "state_quiet",
    pageSystem: { axis: "alternating", surfacePlan: "SP2_continuous_light", border: "hairline", card: "flat", button: "underline" },
    composition: { asymmetry: "gentle", hierarchy: "editorial", rhythm: "continuous", sectionContrast: "low", ornament: "restrained" },
    typography: "heritage_caslon_karla", density: "balanced",
    parameters: { heroSplit: 0.50, heroHeight: "standard", alignOffset: 0, measure: "wide", bandHeight: "thin", motifScale: 1, motifOpacity: 0.22, borderWeight: 1, displayTracking: 0 },
    motifs: [{ id: "botanical", slot: "divider" }, { id: "equestrian", slot: "accent" }],
  },
];
